### ISSUE TITLE
编译成功但无法启动

### ISSUE THREAD

**Issue by geol** [project-openwrt/BaiduPCS-Web#3]
使用的是Openwrt官方18.06.4的源码。编译过程正常，安装时显示如下错误：
Installing BaiduPCS-Web (3.6.8-1) to root...
Installing luci-app-baidupcs-web (1.0.0-1) to root...
Configuring BaiduPCS-Web.
Configuring luci-app-baidupcs-web.
: not foundpkg/info/luci-app-baidupcs-web.postinst: /etc/uci-defaults/luci-baidupcs-web: line 2: 
uci: Entry not found
uci: Parse error (invalid command) at line 1, byte 0
我上来看来下别人提交的BUG，然后使用BaiduPCS-Web命令，结果如下：
root@MiWrt:~# BaiduPCS-Web 
Illegal instruction

**Comment by 1715173329** [comment]
bcm53xx环境可能无法正常运行。

**Comment by 1715173329** [comment]
可能是由于架构原因导致，或者被错误压缩。
可以尝试去源仓库获取二进制文件。
